# IMPORTANT
# https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app

name: Renovate
on:
  push:
  pull_request:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@2d92b2a2bb7030dca3dd14975ae44799debed2e8
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: renovate.json
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'
        env:
          LOG_LEVEL: "debug"
          RENOVATE_USERNAME: ${{ github.repository_owner }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^docker"]'
